services:
  - type: web
    name: eventx-backend
    env: node
    plan: free
    buildCommand: cd eventx-backend && npm install
    startCommand: cd eventx-backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
